<a href="https://colab.research.google.com/github/HusseinWaleed1/lab1/blob/main/Pandas%2BPractice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Part 1

The file "Purchase_Data.csv" contains purchase data at a Chinese supermarket for various products.  Read this csv into a dataframe called df_data and use the head() method to check that you have read in the data correctly. Make sure you import pandas.

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import numpy as np
import pandas as pd
df_data=pd.read_csv('/content/drive/MyDrive/datasets/Purchase_Data.csv')
df_data.head()

,invoice_number,invoice_time,store_id,product_id,category_id,num_item,price
0,2.020000e+11,7/15/15 10:45,G816,7000300,210101,1.0,2.0
1,2.020000e+11,7/15/15 12:16,G816,7070884,70203,1.0,2.0
2,2.020000e+11,7/15/15 12:16,G816,7070884,70203,1.0,2.0
3,2.020000e+11,7/15/15 12:16,G816,7070891,70401,1.0,6.0
4,2.020000e+11,7/15/15 12:16,G816,7090363,70401,1.0,6.0

Use the dtypes attribute to view how each column is stored

In [ ]:
#Write your code here
df_data.dtypes

invoice_number    float64
invoice_time       object
store_id           object
product_id          int64
category_id         int64
num_item          float64
price             float64
dtype: object

Slice the first two columns using .loc and store the result in a variable called result_1.

In [ ]:
#Write you code here
result_1 = df_data.loc[:, df_data.columns[:2]]
result_1

      invoice_number   invoice_time
0       2.020000e+11  7/15/15 10:45
1       2.020000e+11  7/15/15 12:16
2       2.020000e+11  7/15/15 12:16
3       2.020000e+11  7/15/15 12:16
4       2.020000e+11  7/15/15 12:16
...              ...            ...
5377    2.020000e+11   9/5/15 23:07
5378    2.020000e+11   9/5/15 23:23
5379    2.020000e+11   9/5/15 23:24
5380    2.020000e+11   9/5/15 23:32
5381    2.020000e+11   9/5/15 23:38

[5382 rows x 2 columns]

Slice the first two rows using .loc and store the result in a variable called result_2.

In [ ]:
#Write you code here
result_2=df_data.loc[:,df_data.columns[:2]]
result_2

      invoice_number   invoice_time
0       2.020000e+11  7/15/15 10:45
1       2.020000e+11  7/15/15 12:16
2       2.020000e+11  7/15/15 12:16
3       2.020000e+11  7/15/15 12:16
4       2.020000e+11  7/15/15 12:16
...              ...            ...
5377    2.020000e+11   9/5/15 23:07
5378    2.020000e+11   9/5/15 23:23
5379    2.020000e+11   9/5/15 23:24
5380    2.020000e+11   9/5/15 23:32
5381    2.020000e+11   9/5/15 23:38

[5382 rows x 2 columns]

Slice the first four rows and the first five columns and store the result in a variable called result_3.

In [ ]:
#Write your code here
result_3 = df_data.iloc[:4, :5]
result_3

   invoice_number   invoice_time store_id  product_id  category_id
0    2.020000e+11  7/15/15 10:45     G816     7000300       210101
1    2.020000e+11  7/15/15 12:16     G816     7070884        70203
2    2.020000e+11  7/15/15 12:16     G816     7070884        70203
3    2.020000e+11  7/15/15 12:16     G816     7070891        70401

Slice rows 0,4,6 and columns invoice time and price and store the result in variable called result_4.

In [ ]:
df_data.columns

Index(['invoice_number', 'invoice_time', 'store_id', 'product_id',
       'category_id', 'num_item', 'price'],
      dtype='object')

In [ ]:
#Write your code here
result_4 = df_data.loc[[0, 4, 6], ["invoice_time", "price"]]
result_4

    invoice_time  price
0  7/15/15 10:45    2.0
4  7/15/15 12:16    6.0
6  7/15/15 15:28    2.0

Store the number rows in a variable called num_rows.

In [ ]:
num_rows=df_data.shape[0]
num_rows

5382

Print out the last row of the data to dataframe. **Hint:** use the variable num_rows from the previous exercise.

In [ ]:
#Write your code here
last_row = df_data.loc[num_rows - 1]
last_row

invoice_number    202000000000.0
invoice_time        9/5/15 23:38
store_id                    G619
product_id              23030206
category_id               210101
num_item                     1.0
price                        2.0
Name: 5381, dtype: object

# Part 2

Compute the average and max price charged.  Store the results in variables called avg_price and max_price

In [ ]:
avg_price=np.average(df_data['price'])
print('The average price is ',avg_price)
max_price=np.max(df_data['price'])
print('The Maximum price is ',max_price)

The average price is  3.1920522110741363
The Maximum price is  6.01

Compute the average price and average number of items purchased with only a single call to the mean() method. Store these averages in avg_price and avg_num_items.

In [ ]:
#Write you code here
avg_pr=df_data['price'].mean()
print('The average price is ',avg_pr)
avg_num=df_data['num_item'].mean()
print('The average Number is',avg_num)

The average price is  3.1920522110741363
The average Number is 1.2983091787439613

Create a column called "total", which is the product of the price and num_item columns.

In [49]:
#Write your code here
total=df_data['price'].sum() *df_data['num_item'].sum()
print('The total is ',total)

The total is  120042629.68750699

What is the avgerage price of the three most expensive purchases?

In [45]:
#Write your code here
top3_prices = df_data['price'].nlargest(3)
avg_price_top3 = top3_prices.mean()
print("The average price of the three most expensive purchases is", avg_price_top3)

The average price of the three most expensive purchases is 6.003333333333333

How many different products are there?

In [47]:
#Write your code here
num_product=df_data['product_id'].nunique()
num_product

53

Find the difference between the mean and median of the column total.  Use the describe() method and then index the dataframe it returns.

In [53]:
#Write your code here
df_data['total'] = df_data['price'] * df_data['num_item']
stats = df_data['total'].describe()
diff = stats['mean'] - stats['50%']
print("The difference between mean and median of total is", diff)

The difference between mean and median of total is 0.9318078781127839

Use the drop() method to delete the column total from the dataframe df_data.

In [57]:
#Write your code here
df_data.drop(columns='total', inplace=True)
df_data

,invoice_number,invoice_time,store_id,product_id,category_id,num_item,price
0,2.020000e+11,7/15/15 10:45,G816,7000300,210101,1.0,2.0
1,2.020000e+11,7/15/15 12:16,G816,7070884,70203,1.0,2.0
2,2.020000e+11,7/15/15 12:16,G816,7070884,70203,1.0,2.0
3,2.020000e+11,7/15/15 12:16,G816,7070891,70401,1.0,6.0
4,2.020000e+11,7/15/15 12:16,G816,7090363,70401,1.0,6.0
...,...,...,...,...,...,...,...
5377,2.020000e+11,9/5/15 23:07,300,7308017,210101,1.0,3.0
5378,2.020000e+11,9/5/15 23:23,G619,7070891,70401,1.0,6.0
5379,2.020000e+11,9/5/15 23:24,G619,7071096,70201,1.0,5.0
5380,2.020000e+11,9/5/15 23:32,G619,15000231,70301,2.0,2.0
5381,2.020000e+11,9/5/15 23:38,G619,23030206,210101,1.0,2.0

Let's dig a little deeper into the data set and answer some basic question.

In [62]:
#Write your code here
df_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5382 entries, 0 to 5381
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   invoice_number  5382 non-null   float64
 1   invoice_time    5382 non-null   object
 2   store_id        5382 non-null   object
 3   product_id      5382 non-null   int64
 4   category_id     5382 non-null   int64
 5   num_item        5382 non-null   float64
 6   price           5382 non-null   float64
dtypes: float64(3), int64(2), object(2)
memory usage: 294.5+ KB

In [63]:
df_data.describe()

       invoice_number    product_id    category_id     num_item        price
count    5.382000e+03  5.382000e+03    5382.000000  5382.000000  5382.000000
mean     2.020000e+11  8.740911e+06  115465.616499     1.298309     3.192052
std      0.000000e+00  5.048294e+06   65448.435316     2.168725     1.652007
min      2.020000e+11  7.000034e+06   70101.000000     0.500000     0.000000
25%      2.020000e+11  7.070884e+06   70201.000000     1.000000     2.000000
50%      2.020000e+11  7.071096e+06   70401.000000     1.000000     2.500000
75%      2.020000e+11  7.090592e+06  210101.000000     1.000000     5.000000
max      2.020000e+11  3.000077e+07  210301.000000   116.000000     6.010000

In [66]:
df_data.isnull().sum()

invoice_number    0
invoice_time      0
store_id          0
product_id        0
category_id       0
num_item          0
price             0
dtype: int64

In [67]:
df_data.shape

(5382, 7)

First, covert the column invoice time to a datetime column. Print out the new column types to make sure this was done correctly

In [68]:
df_data.columns

Index(['invoice_number', 'invoice_time', 'store_id', 'product_id',
       'category_id', 'num_item', 'price'],
      dtype='object')

In [71]:
#Write your code here
df_data.rename(columns={'invoice_time':'date_time'},inplace=True)
df_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5382 entries, 0 to 5381
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   invoice_number  5382 non-null   float64
 1   date_time       5382 non-null   object
 2   store_id        5382 non-null   object
 3   product_id      5382 non-null   int64
 4   category_id     5382 non-null   int64
 5   num_item        5382 non-null   float64
 6   price           5382 non-null   float64
dtypes: float64(3), int64(2), object(2)
memory usage: 294.5+ KB

Next, let's create columns called "DOW" and "Month", which store the corresponding weekday and month of the invoice respectively.  Print the head of the dataframe to make sure this was done correctly.

In [72]:
#Write your code here
df_data['date_time'] = pd.to_datetime(df_data['date_time'])
df_data['DOW'] = df_data['date_time'].dt.day_name()
df_data['Month'] = df_data['date_time'].dt.month_name()
print(df_data.head())

/tmp/ipython-input-251376494.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_data['date_time'] = pd.to_datetime(df_data['date_time'])

   invoice_number           date_time store_id  product_id  category_id  \
0    2.020000e+11 2015-07-15 10:45:00     G816     7000300       210101
1    2.020000e+11 2015-07-15 12:16:00     G816     7070884        70203
2    2.020000e+11 2015-07-15 12:16:00     G816     7070884        70203
3    2.020000e+11 2015-07-15 12:16:00     G816     7070891        70401
4    2.020000e+11 2015-07-15 12:16:00     G816     7090363        70401

   num_item  price        DOW Month
0       1.0    2.0  Wednesday  July
1       1.0    2.0  Wednesday  July
2       1.0    2.0  Wednesday  July
3       1.0    6.0  Wednesday  July
4       1.0    6.0  Wednesday  July

Create a variable called num_purchases_wed, which stores the number of purchases made on Wednesday?  You should use value_counts and then index the series it return.

In [73]:
#Write your code here
num_purchases_wed = df_data['DOW'].value_counts()['Wednesday']
print("Number of purchases on Wednesday:", num_purchases_wed)

Number of purchases on Wednesday: 959

# Part 3

In this set of practice exercises, we will be working with a demographic data regarding the passengers aboard the Titanic.  Read in the data frame and use the head() method to check that it was read in correctly.

In [74]:
#Write your code here
df=pd.read_csv('/content/drive/MyDrive/datasets/Titanic.csv')
df.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

Use the rename method to change the column "Name" to "Passenger_Name" and the column "Ticket" to "Ticket_Num".

In [77]:
#Write your code here
df.rename(columns={'Name':'Passenger_Name', 'Ticket':'Ticket_Num'}, inplace=True)
df.head()

,PassengerId,Pclass,Passenger_Name,Sex,Age,SibSp,Parch,Ticket_Num,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

Change the index of the df_titanic to the column PasengerID.

In [79]:
#Write your code here
df = df.set_index("PassengerId")
print(df.head())

             Pclass                                Passenger_Name     Sex  \
PassengerId
892               3                              Kelly, Mr. James    male
893               3              Wilkes, Mrs. James (Ellen Needs)  female
894               2                     Myles, Mr. Thomas Francis    male
895               3                              Wirz, Mr. Albert    male
896               3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female

              Age  SibSp  Parch Ticket_Num     Fare Cabin Embarked
PassengerId
892          34.5      0      0     330911   7.8292   NaN        Q
893          47.0      1      0     363272   7.0000   NaN        S
894          62.0      0      0     240276   9.6875   NaN        Q
895          27.0      0      0     315154   8.6625   NaN        S
896          22.0      1      1    3101298  12.2875   NaN        S

Select the name of passenger 896

In [80]:
#Write your code here
passenger_896_name = df.loc[896, "Passenger_Name"]
print("The name of passenger 896 is:", passenger_896_name)

The name of passenger 896 is: Hirvonen, Mrs. Alexander (Helga E Lindqvist)

Change the index back to row numbers but making sure that we don't lose the PassengerId column.

In [81]:
#Write your code here
df = df.reset_index()
print(df.head())

   PassengerId  Pclass                                Passenger_Name     Sex  \
0          892       3                              Kelly, Mr. James    male
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female
2          894       2                     Myles, Mr. Thomas Francis    male
3          895       3                              Wirz, Mr. Albert    male
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female

    Age  SibSp  Parch Ticket_Num     Fare Cabin Embarked
0  34.5      0      0     330911   7.8292   NaN        Q
1  47.0      1      0     363272   7.0000   NaN        S
2  62.0      0      0     240276   9.6875   NaN        Q
3  27.0      0      0     315154   8.6625   NaN        S
4  22.0      1      1    3101298  12.2875   NaN        S

How many missing entries are there in the Age column? Use the isnull() method and recall than Booleans are exactly like 1s (True) and 0s (False).

In [84]:
num_missing_age = df['Age'].isnull().sum()
print("Number of missing entries in Age column:", num_missing_age)

Number of missing entries in Age column: 86

Compute the avg age of passengers ignoring the missing data.

In [85]:
#Write your code here
avg_age = df['Age'].mean()
print("The average age of passengers is:", avg_age)

The average age of passengers is: 30.272590361445783

Using the fillna() method replace the missing values in the Age column with the mean.

In [86]:
#Write your code here
df['Age'] = df['Age'].fillna(df['Age'].mean())
print(df['Age'].isnull().sum())

0

What is the average age of the 5 oldest passengers? The reset_index method will be helpful here.

In [87]:
#Write your code here
oldest_5 = df.sort_values('Age', ascending=False).reset_index()
avg_age_oldest_5 = oldest_5.loc[:4, 'Age'].mean()
print("The average age of the 5 oldest passengers is:", avg_age_oldest_5)

The average age of the 5 oldest passengers is: 67.0